name: quant_alpha
version: "1.0.0"
config-version: 2

profile: quant_alpha

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  quant_alpha:
    staging:
      +materialized: view
    marts:
      +materialized: table
