{{- if and .Values.secrets.create (not .Values.secrets.external) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quant-alpha.secretName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "quant-alpha.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
